#!/bin/bash

set -o errexit
set -o nounset

curl -s https://tomeichlersmith.github.io/denv/install | sh

echo "::group::initialize environment"
denv init ${1}
echo "::endgroup::"

echo "::group::clone ldmx-sw"
git clone  --recursive --branch ${2} https://github.com/LDMX-Software/ldmx-sw.git
echo "::endgroup::"

echo "::group::patch ldmx-sw"
patch_file="ci/interop/${2}.patch"
if [ -f "${patch_file}" ]; then
  echo "applying ${patch_file}"
  git -C ldmx-sw apply "../${patch_file}"
else
  echo "no patches found (${patch_file} does not exist)"
fi
echo "::endgroup::"

echo "::group::build ldmx-sw"
denv cmake -B ldmx-sw/build -S ldmx-sw
denv cmake --build ldmx-sw build
echo "::endgroup::"

echo "::group::basic simulation run"
denv fire ldmx-sw/SimCore/test/basic.py
echo "::endgroup::"
