
name: Build

# only build if push changes to files involved in the build
on:
  push:
    branches: [ main , unification ]
    paths: [ 'ldmx.sh' , 'Dockerfile' , 'install-scripts/**' , '**base.yml' ]

# the jobs are the different container tags that we want built
jobs:
  # basic, defaults development container
  #     this is the container that pretty much everyone in ldmx-sw should use
  basic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build It!
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ldmx/dev
        tags: unification

  # newer version of Geant4
  #     allow for developers to have access to a container with Geant4.10.6 in it
  geant4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build It!
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ldmx/dev
        build_args: GEANT4=geant4-10.6-release
        tags: uni.geant4.10.6
