
name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
    branches:
      - '**'
    tags:
      - 'v*.*'

# workflow consists of one building and testing job
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Cache Docker Layers on GitHub
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx
    - 
      name: Get Build Context
      uses: actions/checkout@v3
    -
      name: Build the Image
      uses: docker/build-push-action@v3
      with:
        push: false # don't push to docker hub yet
        load: true # allow image to be availabe to the docker program later in this job
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: new-build
    -
      name: Package Image
      run: docker save new-build > ldmx-dev.tar
    - 
      name: Upload Newly Built Image
      uses: actions/upload-artifact@v3
      with:
        name: ldmx-dev-${{ github.sha }}
        path: ldmx-dev.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ldmx_sw_branch: [ trunk, v3.0.0, v3.0.2, v3.1.0, v3.1.13 ]
    defaults:
      run:
        shell: bash
    steps:
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Download Image
      uses: actions/download-artifact@v3
      with:
        name: ldmx-dev-${{ github.sha }}
    - 
      name: Import Image into Docker
      run: docker load --input ldmx-dev.tar
    -
      name: Download Build Context for Test Script
      uses: actions/checkout@v3
    -
      name: Pull down ldmx-sw for testing
      uses: actions/checkout@v3
      with:
        repository: LDMX-Software/ldmx-sw
        submodules: recursive
        path: ldmx-sw
        ref: ${{ matrix.ldmx_sw_branch }}
        fetch-depth: 0
    - 
      name: Test the Image
      run: |
          export LDMX_BASE=$(pwd)
          export _docker_parameters="-i -e LDMX_BASE -v $LDMX_BASE:$LDMX_BASE new-build"
          mkdir ldmx-sw/build
          curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh \
            -o semver.sh
          #I can't figure out how to get the tag of a submodule after the specific method of cloning
          #  GitHub actions uses, for this reason I'm just going to use the ldmx-sw tag
          #_curr=$(git -C ldmx-sw/Framework fetch && git -C ldmx-sw/Framework describe --tags)
          _curr=$(git -C ldmx-sw describe --tags)
          _order=$(sh semver.sh ${_curr} v3.2.0)
          if [ "$?" == "-1" ]; then
            # need to update Framework for patches with newer compiler
            echo "::group::Updating Framework from ${_curr}"
            git -C ldmx-sw/Framework checkout v1.3.1
            echo "::endgroup::"
          fi
          echo "::group::Build ldmx-sw"
          docker run $_docker_parameters $(pwd)/ldmx-sw/build 'cmake .. && make install'
          echo "::endgroup::"
          echo "::group::Run python test script"
          docker run $_docker_parameters $(pwd) python3 test.py
          echo "::endgroup::"
          echo "::group::ldmx-sw test program"
          docker run $_docker_parameters $(pwd)/ldmx-sw/build ctest --verbose
          echo "::endgroup::"

  push:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Determine Image Tags
      id: generate_tag
      run: |
          _repo=ldmx/dev
          _tag=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # if pushing a git tag ==> get the git tag for the docker tag
            _tag=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            # pushing to a branch ==> docker tag is branch name
            #   if branch name is default_branch, docker tag is 'edge'
            _tag=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$_tag" ]; then
              _tag=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            # pull request branch ==> docker tag is pr number
            _tag=pr-${{ github.event.number }}
          fi
          _push_tags="${_repo}:${_tag}"
          if [[ $_tag =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            # latest docker tag is latest version built matching the format 
            #   v<1-3 digits>.<1-3 digits>.<1-3 digits>
            # we the major.minor tag as well to reflect that old patches
            #   generally should be abandoned
            _push_tags="$_push_tags ${_repo}:${_tag%.*} ${_repo}:latest"
          elif [ "${{ github.event_name }}" = "push" ]; then
            # on push actions, tag with sha of GITHUB as well
            _push_tags="$_push_tags ${_repo}:sha-${GITHUB_SHA::8}"
          fi
          echo "Generated Tags: ${_push_tags}"
          echo "push_tags=${_push_tags}" >> $GITHUB_OUTPUT
    -
      name: Download Image
      uses: actions/download-artifact@v3
      with:
        name: ldmx-dev-${{ github.sha }}
    - 
      name: Import Image into Docker
      run: docker load --input ldmx-dev.tar
    -
      name: Push Build to DockerHub
      run: |
        for tag in ${{ steps.generate_tag.outputs.push_tags }}; do 
          docker tag new-build $tag
          docker push $tag 
        done
