
name: Derivatives

on:
  push:
    branches: [ master ]
    paths: [ 'derivatives/**' ]

jobs:
  uproot:
    steps:
    - uses: actions/checkout@v2
    - run: cd derivatives
    - name: Build It!
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ldmx/dev
        dockerfile: Dockerfile.uproot
        tags: uproot

