
name: Derivatives

on:
  push:
    branches: [ master ]
    paths: [ '**/derivatives.yml' , 'derivatives/**' ]
 
jobs:
  uproot:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: derivatives
    steps:
    - uses: actions/checkout@v2
    - name: Build It!
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ldmx/dev
        dockerfile: Dockerfile.uproot
        tags: uproot

