
name: Geant4.10.6

# only build if push changes something other than README or derivatives
on:
  push:
    branches: [ main ]
    paths: [ 'ldmx.sh' , 'Dockerfile' , 'install-scripts/**' , '**geant4.yml' ]

# build the two "base" images in parallel
# one uses the default versions and the other uses a more recent version of Geant4
jobs:
  geant4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build It!
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ldmx/dev
        build_args: GEANT4=geant4-10.6-release
        tags: geant4.10.6
