---

name: Test ldmx-sw Dependabot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight
  push:

jobs:
  check-on-runner-releases:
    permissions: write-all
#      pull-requests: write
#      contents: write
#      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: fetch latest releases
        run: |
          ./ci/ldmx-sw-dependabot --apply 
          git config --global user.name ldmx-sw-test-bot
          git config --global user.email ldmx-sw-test-bot@users.noreply.github.com
          git switch -c auto-ldmx-sw-test-update
          git add ci/ldmx-sw-to-test.json
          git commit -m "Auto ldmx-sw Version Update" || exit 0
          git push -u origin auto-runner-update
          gh pr create \
            --base main \
            --head auto-runner-update \
            --title "Auto ldmx-sw Version Update" \
            --body "Written by custom dependabot script that checks for new updates. PR now free to be modified/closed."
        env:
          GH_TOKEN: ${{ github.token }}
