---

name: Test ldmx-sw Dependabot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight

jobs:
  check-on-runner-releases:
    permissions:
      pull-requests: write
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: fetch latest releases
        run: |
          ./ci/ldmx-sw-dependabot
          git config --global user.name ldmx-sw-test-bot
          git config --global user.email ldmx-sw-test-bot@users.noreply.github.com
          git switch -c auto-ldmx-sw-test-update
          git add ci/
          git commit -m "Auto ldmx-sw Version Update" || exit 0
          git push -fu origin auto-ldmx-sw-test-update
          gh pr create \
            --base main \
            --head auto-ldmx-sw-test-update \
            --title "Auto ldmx-sw Version Update" \
            --body "Written by custom dependabot script that checks for new updates. PR now free to be modified/closed."
        env:
          GH_TOKEN: ${{ github.token }}
