
name: Base

# only build if push changes to files involved in the base build
on:
  push:
    branches: [ master ]
    paths: [ 'ldmx.sh' , 'Dockerfile' , 'install-scripts/**' , '**pyroot2.yml' ]

# build the two "base" images in parallel
# one uses the default versions and the other uses a more recent version of Geant4
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build It!
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ldmx/dev
        build_args: PyROOT_PyVersion=2
        tags: pyroot2
