
name: Build

# only build if push changes to files involved in the build
on:
  pull_request:
    branches: [ main ]

# make sure the changes can build and run ldmx-sw
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build It!
      run: docker build . -t ldmx/dev:testing

    - name: Get ldmx-sw
      uses: actions/checkout@v2
      with:
          repository: 'LDMX-Software/ldmx-sw'
          submodules: 'recursive'
      working-directory: test

    - name: Configure the build
      run: |
          mkdir build &&
          docker run -i -v $(pwd):$(pwd) ldmx/dev:testing $(pwd)/build cmake -DBUILD_TESTS=ON ..
      working-directory: test/ldmx-sw

    - name: Build and Install
      run: docker run -i -v $(pwd):$(pwd) ldmx/dev:testing $(pwd)/build make install
      working-directory: test/ldmx-sw

    - name: Test the build
      run: |
          export LDMX_BASE=$(pwd) &&
          docker run -i -e LDMX_BASE -v $(pwd):$(pwd) ldmx/dev:testing $LDMX_BASE/ldmx-sw/install ./bin/run_test
      working-directory: test

    - name: Test the python
      run: |
          export LDMX_BASE=$(pwd) &&
          docker run -i -e LDMX_BASE -v $(pwd):$(pwd) ldmx/dev:testing . python  test.py &&
          docker run -i -e LDMX_BASE -v $(pwd):$(pwd) ldmx/dev:testing . python3 test.py
      working-directory: test
